### ISSUE TITLE
USER STORY: Run at the weekend

### ISSUE THREAD

**Issue by HumaIlyas** [HumaIlyas/love-running#4]
As a **runner** I would **love to run** at the **weekend**, so that I can **keep myself fit**. Is that **possible**?

### Acceptance Criteria
* Acceptance Criteria 1: If more people will be interested to run at the weekend
* Acceptance Criteria 2: What time suits best to all of them
* Acceptance Criteria 3: What if we want to make it possible at alternate weekend

### Tasks 
- [x] Task 1: To decide and display the time 
- [x] Task 2: To decide and display the place 
- [x] Task 3: To decide and display how much Km to run
- [x] Task 4: To encourage people to run at the weekend through campaign
